## Lists Recap
- Powerful
- Collection of values
- Hold different types
- Change, add, remove

Minus points as need for Data Science:
- Mathematical operations over collections
- Speed


## Illustration Problem

In [5]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

print(height)
print(weight)

[1.73, 1.68, 1.71, 1.89, 1.79]
[65.4, 59.2, 63.6, 88.4, 68.7]


In [6]:
# calculating BMI, there an error
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## Solution: NumPy
- Numeric Python
- Alternative to Python lists: NumPy array
- Calculations over entire arrays
- Easy and Fast

## NumPy

In [7]:
import numpy as np

In [9]:
np_height = np.array(height)
np_weight = np.array(weight)

print(np_height)
print(np_weight)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [5]:
# Calculate BMI
bmi = np_weight / np_height ** 2
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


## NumPy: Remarks
- NumPy arrays: contain only one type
- Different types: different behavior

In [ ]:
# Contain only one type
print(np.array([1.0, "is", True])) # all change to string

['1.0' 'is' 'True']


In [ ]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])


In [ ]:
python_list + python_list
# Menambahkan list Python dengan dirinya sendiri, menghasilkan pengulangan elemen-elemen list.


[1, 2, 3, 1, 2, 3]

In [ ]:
numpy_array + numpy_array
# Menambahkan array NumPy dengan dirinya sendiri, yang menghasilkan penjumlahan elemen-elemen array secara elemen per elemen.


array([2, 4, 6])

## NumPy Subsetting

In [10]:
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [11]:
print(bmi[1])

20.97505668934241


In [12]:
print(bmi > 23)

[False False False  True False]


In [13]:
print(bmi[bmi > 23])

[24.7473475]
