In [36]:
import numpy as np
import random

v = np.empty(100)
w = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data1 = np.array([1, 2, 3, 4, 100])
data2 = np.array([1, 2, 3, 4, 5])
x = np.array([10, 20, 30, 40, 50])
array1 = np.array([[1, 2, 3],
                [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                [10, 11, 12]])
y = np.array([[1, 2, 3],
              [4, 5, 6]])
z = np.array([1, 2, 3, 4, 5])

In [2]:
print(np.array([10, 20, 30]))

[10 20 30]


In [6]:
print(z[1:4:2])

[2 4]


In [8]:
print(y)

[[1 2 3]
 [4 5 6]]


In [9]:
print(y[0][1])

2


In [15]:
print(array1 + array2)

[[ 8 10 12]
 [14 16 18]]


In [18]:
print(np.mean(x))

30.0


In [19]:
print(np.median(x))

30.0


In [23]:
print(np.mean(data1), np.median(data1))
print(np.mean(data2), np.median(data2))

22.0 3.0
3.0 3.0


In [29]:
print(w[w > 5])
        

[ 6  7  8  9 10]


In [41]:
v = np.random.randint(1, 101, 100)
print(np.mean(v), np.median(v), np.std(v))


46.84 46.5 27.174149480710522
