In [29]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

t = np.array([1, 2, 3, 4, 100])

u = np.array([10, 20, 30, 40, 50])

v = np.array([
    [5, 6],
    [7, 8]
])

w = np.array([
    [1, 2],
    [3, 4]
])

x = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])

y = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

z = np.array([1, 2, 3, 4, 5])


In [7]:
print(z)

[1 2 3 4 5]


In [9]:
z[0] = 10
print(z)

[10  2  3  4  5]


In [12]:
print(y[1:10:2])

[1 3 5 7 9]


In [16]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(x[1][2])

6


In [20]:
print(v + w)

[[ 6  8]
 [10 12]]


In [22]:
print(np.mean(u))

30.0


In [23]:
print(np.median(u))

30.0


In [26]:
print(np.mean(t))
print(np.median(t))

22.0
3.0


In [28]:
print(a * b)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
