In [2]:
import numpy as np

list_angka_h4np = [
    10,
    20,
    30,
    40,
    50,
]

array_numpy_pertama_h4np = np.array(list_angka_h4np)
print(array_numpy_pertama_h4np)
print(array_numpy_pertama_h4np.dtype)

[10 20 30 40 50]
int64


In [3]:
list_desimal_h4np = [
    1.0,
    2.5,
    3.0,
    4.75,
    5.25,
]

array_float_h4np = np.array(list_desimal_h4np)
print(array_float_h4np.dtype)

array_integer_eksplisit_h4np = np.array(list_desimal_h4np, dtype=np.int32)
print(array_integer_eksplisit_h4np)
print(array_integer_eksplisit_h4np.dtype)

float64
[1 2 3 4 5]
int32


In [ ]:
array_awal_h4np = np.array([
    5,
    10,
    15,
    20,
])

array_hasil_penambahan_h4np = array_awal_h4np + 2
print(array_awal_h4np)
print(array_hasil_penambahan_h4np)

# array_awal_h4np tidak berubah karena operasi penambahan skalar (array_awal_h4np + 2) menghasilkan array baru, dan tidak memodifikasi array asli secara langsung.

[ 5 10 15 20]
[ 7 12 17 22]


In [8]:
nilai_ujian_h4np = np.array([
    70,
    85,
    92,
    65,
    78,
    90,
    88,
])

nilai_pertama_h4np = nilai_ujian_h4np[0]
nilai_terakhir_h4np = nilai_ujian_h4np[-1]
tiga_nilai_pertama_h4np = nilai_ujian_h4np[:3]
nilai_tengah_h4np = nilai_ujian_h4np[2:5]

print(nilai_pertama_h4np)
print(nilai_terakhir_h4np)
print(tiga_nilai_pertama_h4np)
print(nilai_tengah_h4np)

70
88
[70 85 92]
[92 65 78]


In [9]:
data_matriks_h4np = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

array_2d_h4np = np.array(data_matriks_h4np)
print(array_2d_h4np)
print(array_2d_h4np.shape)
print(array_2d_h4np.ndim)
print(array_2d_h4np.size)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9


In [ ]:
elemen_1_2_h4np = array_2d_h4np[0, 1]
baris_kedua_h4np = array_2d_h4np[1]
kolom_ketiga_h4np = array_2d_h4np[:, 2]

sub_matriks_2x2_h4np = array_2d_h4np[0:2, 0:2]

print(elemen_1_2_h4np)
print(baris_kedua_h4np)
print(kolom_ketiga_h4np)
print(sub_matriks_2x2_h4np)

2
[4 5 6]
[3 6 9]
[[1 2]
 [4 5]]


In [12]:
matriks_a_h4np = np.array([
    [10, 20],
    [30, 40],
])

matriks_b_h4np = np.array([
    [2, 3],
    [4, 5],
])

hasil_tambah_matriks_h4np = matriks_a_h4np + matriks_b_h4np
hasil_kali_matriks_h4np = matriks_a_h4np * matriks_b_h4np
matriks_a_dikali_3_h4np = matriks_a_h4np * 3

print(hasil_tambah_matriks_h4np)
print(hasil_kali_matriks_h4np)
print(matriks_a_dikali_3_h4np)

[[12 23]
 [34 45]]
[[ 20  60]
 [120 200]]
[[ 30  60]
 [ 90 120]]


In [13]:
data_pengukuran_h4np = np.array([
    10.5,
    12.0,
    11.5,
    13.0,
    10.0,
    14.5,
    12.5,
    11.0,
])

rata_rata_pengukuran_h4np = np.mean(data_pengukuran_h4np)
total_pengukuran_h4np = np.sum(data_pengukuran_h4np)
min_pengukuran_h4np = np.min(data_pengukuran_h4np)
max_pengukuran_h4np = np.max(data_pengukuran_h4np)

print(f"Rata-rata pengukuran: {rata_rata_pengukuran_h4np}")
print(f"Total pengukuran: {total_pengukuran_h4np}")
print(f"Nilai minimum: {min_pengukuran_h4np}")
print(f"Nilai maksimum: {max_pengukuran_h4np}")

Rata-rata pengukuran: 11.875
Total pengukuran: 95.0
Nilai minimum: 10.0
Nilai maksimum: 14.5


In [14]:
median_pengukuran_h4np = np.median(data_pengukuran_h4np)
std_dev_pengukuran_h4np = np.std(data_pengukuran_h4np)

print(f"Median: {median_pengukuran_h4np}")
print(f"Standar Deviasi: {std_dev_pengukuran_h4np}")

Median: 11.75
Standar Deviasi: 1.3635890143294642


In [ ]:
gaji_karyawan_h4np = np.array([
    20,
    22,
    25,
    23,
    28,
    26,
    150,
])

rata_rata_gaji_h4np = np.mean(gaji_karyawan_h4np)
median_gaji_h4np = np.median(gaji_karyawan_h4np)
print(f"Rata-rata gaji: {rata_rata_gaji_h4np}")
print(f"Median gaji: {median_gaji_h4np}")

# karena ada nilai ekstrim(outliers)
# lebih baik gunakan nilai median, karena median tidak terpengaruh oleh nilai ekstrim(outliers)


Rata-rata gaji: 42.0
Median gaji: 25.0
