### Soal 1: Membuat NumPy Array dari List

1.  Impor *package* NumPy dan berikan ia alias **`np`**.
2.  Buatlah sebuah Python list biasa bernama **`curah_hujan_pl_h5`** yang berisi data curah hujan (dalam mm) selama seminggu: `[20.5, 15.0, 5.2, 0.0, 30.7, 45.1, 10.0]`.
3.  Konversikan `curah_hujan_pl_h5` tersebut menjadi sebuah NumPy array bernama **`hujan_array_np_h5`**.
4.  Tampilkan `hujan_array_np_h5`.
5.  Tampilkan juga atribut **`.shape`** dan **`.dtype`** dari `hujan_array_np_h5`.

In [1]:
import numpy as np

curah_hujan_pl_h5 = [
    20.5,
    15.0,
    5.2,
    0.0,
    30.7,
    45.1,
    10.0,
]
hujan_array_np_h5 = np.array(curah_hujan_pl_h5)
print(hujan_array_np_h5)
print(hujan_array_np_h5.shape)
print(hujan_array_np_h5.dtype)

[20.5 15.   5.2  0.  30.7 45.1 10. ]
(7,)
float64


### Soal 2: Membuat Array dengan Tipe Data Eksplisit

1.  Impor NumPy sebagai `np`.
2.  Buatlah sebuah Python list bernama **`jumlah_pengunjung_np_h5`** yang berisi data pengunjung (integer): `[120, 155, 200, 95, 130]`.
3.  Buatlah sebuah NumPy array bernama **`pengunjung_float_np_h5`** dari list tersebut, tetapi secara eksplisit tentukan tipe datanya (`dtype`) menjadi **`np.float64`** saat pembuatan array.
4.  Tampilkan `pengunjung_float_np_h5`.
5.  Tampilkan juga atribut `.dtype` dari `pengunjung_float_np_h5` untuk memverifikasi bahwa tipe datanya memang float, meskipun data aslinya adalah integer.

In [5]:
import numpy as np

jumlah_pengunjung_np_h5 = [120, 155, 200, 95, 130]
pengunjung_float_np_h5 = np.array(jumlah_pengunjung_np_h5, dtype=np.float64)
print(pengunjung_float_np_h5)
print(pengunjung_float_np_h5.dtype)

[120. 155. 200.  95. 130.]
float64


### Soal 3: Operasi Vektorisasi dan "Side Effect"

1.  Impor NumPy sebagai `np`.
2.  Buatlah sebuah NumPy array bernama **`suhu_ruangan_np_h5`** dengan nilai `[28, 31, 33, 30, 29, 27]`.
3.  Lakukan operasi perbandingan pada `suhu_ruangan_np_h5` untuk memeriksa suhu mana saja yang berada di atas 30 derajat. Hasil dari operasi ini (misalnya, `suhu_ruangan_np_h5 > 30`) adalah sebuah array boolean.
4.  Simpan array boolean hasil perbandingan tersebut ke dalam variabel **baru** bernama **`suhu_panas_np_h5`**.
5.  Tampilkan `suhu_ruangan_np_h5` (array asli) dan `suhu_panas_np_h5` (array boolean hasil operasi).
6.  Amati dan jelaskan dalam komentar singkat di kode Anda mengapa `suhu_ruangan_np_h5` tidak berubah, dan apa isi dari `suhu_panas_np_h5`.

In [ ]:
import numpy as np

suhu_ruangan_np_h5 = np.array([28, 31, 33, 30, 29, 27])
suhu_panas_np_h5 = suhu_ruangan_np_h5 > 30

print(suhu_ruangan_np_h5)
print(suhu_panas_np_h5)

# nilai pada array suhu ruangan tidak berubah karena hasil dari operasi logika diatas adalah array baru

[28 31 33 30 29 27]
[False  True  True False False False]


### Soal 4: Subsetting dengan Array Boolean

1.  Gunakan dua array dari Soal 3:
    * `suhu_ruangan_np_h5` (berisi `[28, 31, 33, 30, 29, 27]`)
    * `suhu_panas_np_h5` (berisi `[False, True, True, False, False, False]`)
2.  Gunakan `suhu_panas_np_h5` sebagai "filter" atau indeks untuk mengambil hanya elemen-elemen dari `suhu_ruangan_np_h5` yang suhunya di atas 30.
3.  Simpan hasil subsetting ini ke dalam variabel baru bernama **`daftar_suhu_panas_np_h5`**.
4.  Tampilkan `daftar_suhu_panas_np_h5`.

In [13]:
daftar_suhu_panas_np_h5 = suhu_ruangan_np_h5[suhu_ruangan_np_h5 > 30]
print(daftar_suhu_panas_np_h5)

[31 33]


### Soal 5: Membuat dan Memeriksa Array 2D

1.  Impor NumPy sebagai `np`.
2.  Buatlah sebuah Python list berisi list-of-lists bernama **`penjualan_harian_np_h5`**. Data ini merepresentasikan penjualan 3 produk selama 4 hari.
    ```python
    [
        [10, 15, 12, 18],  # Produk A
        [20, 22, 25, 21],  # Produk B
        [14, 16, 13, 15]   # Produk C
    ]
    ```
3.  Konversikan `penjualan_harian_np_h5` menjadi sebuah NumPy array 2D bernama **`matriks_penjualan_np_h5`**.
4.  Tampilkan `matriks_penjualan_np_h5`.
5.  Tampilkan atribut **`.shape`** dan **`.ndim`** dari `matriks_penjualan_np_h5` untuk memverifikasi bentuk dan jumlah dimensinya.

In [1]:
import numpy as np

penjualan_harian_np_h5 = [
    [10, 15, 12, 18],
    [20, 22, 25, 21],
    [14, 16, 13, 15]
]

matriks_penjualan_np_h5 = np.array(penjualan_harian_np_h5)
print(matriks_penjualan_np_h5)
print(matriks_penjualan_np_h5.shape)
print(matriks_penjualan_np_h5.ndim)

[[10 15 12 18]
 [20 22 25 21]
 [14 16 13 15]]
(3, 4)
2


### Soal 6: Subsetting Array 2D

Gunakan array 2D `matriks_penjualan_np_h5` dari Soal 5.
(Arraynya: `[[10, 15, 12, 18], [20, 22, 25, 21], [14, 16, 13, 15]]`)

1.  Akses dan tampilkan data penjualan **Produk B** (baris kedua) pada **hari ketiga**. (Ingat, indeks dimulai dari 0). Simpan hasilnya dalam variabel **`penjualan_b_hari3_np_h5`**.
2.  Akses dan tampilkan seluruh data penjualan pada **hari keempat** (kolom terakhir). Simpan hasilnya dalam variabel **`penjualan_hari4_np_h5`**.
3.  Akses dan tampilkan seluruh data penjualan untuk **Produk A** (baris pertama). Simpan hasilnya dalam variabel **`penjualan_produk_a_np_h5`**.
4.  Tampilkan semua variabel hasil (`penjualan_b_hari3_np_h5`, `penjualan_hari4_np_h5`, dan `penjualan_produk_a_np_h5`).

In [4]:
penjualan_b_hari3_np_h5 = matriks_penjualan_np_h5[1, 2]
penjualan_hari4_np_h5 = matriks_penjualan_np_h5[:, -1]
penjualan_produk_a_np_h5 = matriks_penjualan_np_h5[0]

print(penjualan_b_hari3_np_h5)
print(penjualan_hari4_np_h5)
print(penjualan_produk_a_np_h5)

25
[18 21 15]
[10 15 12 18]


### Soal 7: Aritmatika pada Array 2D (Revisi)

Variabel `matriks_penjualan_np_h5` sudah ada dari soal sebelumnya.

1.  Buatlah array 1D **`harga_produk_np_h5`** yang berisi harga satuan untuk setiap produk: `[5000, 8000, 12000]`. (Harga ini sesuai dengan urutan produk pada `matriks_penjualan_np_h5`).
2.  Bentuk (shape) dari `matriks_penjualan_np_h5` (`(3, 4)`) dan `harga_produk_np_h5` (`(3,)`) tidak cocok untuk perkalian elemen-demi-elemen secara langsung. Ubah bentuk `harga_produk_np_h5` agar bisa di-*broadcast* dengan benar saat dikalikan. Anda perlu mengubahnya menjadi array kolom dengan shape `(3, 1)`. Gunakan metode `.reshape()`. Simpan hasilnya ke **`harga_produk_kolom_np_h5`**.
3.  Lakukan perkalian antara `matriks_penjualan_np_h5` dan `harga_produk_kolom_np_h5`. NumPy akan secara otomatis melakukan *broadcasting*. Simpan hasilnya, yang merupakan total pendapatan per item per hari, ke dalam variabel **`matriks_pendapatan_np_h5`**.
4.  Tampilkan `matriks_pendapatan_np_h5`.

In [ ]:
harga_produk_np_h5 = np.array([5000, 8000, 12000])
harga_produk_kolom_np_h5 = harga_produk_np_h5.reshape(3, 1)
matriks_pendapatan_np_h5 = matriks_penjualan_np_h5 * harga_produk_kolom_np_h5
print(matriks_pendapatan_np_h5)

[[ 50000  75000  60000  90000]
 [160000 176000 200000 168000]
 [168000 192000 156000 180000]]


### Soal 8: Statistik dengan Sumbu (Axis)

**Asumsi:** Variabel `matriks_pendapatan_np_h5` sudah ada dari soal sebelumnya.

1.  Hitung **total pendapatan per hari** dengan menjumlahkan semua pendapatan di setiap kolom pada `matriks_pendapatan_np_h5`. Gunakan fungsi `np.sum()` dengan argumen `axis` yang tepat. Simpan hasilnya ke dalam variabel **`pendapatan_per_hari_np_h5`**.
2.  Hitung **total pendapatan per produk** dengan menjumlahkan semua pendapatan di setiap baris pada `matriks_pendapatan_np_h5`. Gunakan fungsi `np.sum()` dengan argumen `axis` yang tepat. Simpan hasilnya ke dalam variabel **`pendapatan_per_produk_np_h5`**.
3.  Hitung **total pendapatan keseluruhan** dari semua penjualan. Simpan hasilnya ke dalam variabel **`total_pendapatan_semua_np_h5`**.
4.  Tampilkan ketiga variabel hasil tersebut dengan pesan yang jelas.

In [16]:
pendapatan_per_hari_np_h5 = np.sum(matriks_pendapatan_np_h5, axis=0)
pendapatan_per_produk_np_h5 = np.sum(matriks_pendapatan_np_h5, axis=1)
total_pendapatan_keseluruhan_np_h5 = np.sum(pendapatan_per_produk_np_h5)
print(f"Pendapatan per hari: {pendapatan_per_hari_np_h5}")
print(f"Pendapatan per produk: {pendapatan_per_produk_np_h5}")
print(f"Total pendapatan keseluruhan: {total_pendapatan_keseluruhan_np_h5}")


Pendapatan per hari: [378000 443000 416000 438000]
Pendapatan per produk: [275000 704000 696000]
Total pendapatan keseluruhan: 1675000


### Soal 9: Statistik Dasar Lainnya

1.  Buatlah sebuah NumPy array 1D bernama **`data_tinggi_badan_np_h5`** yang berisi data tinggi badan (dalam cm) dari sekelompok sampel: `[165, 170, 155, 180, 168, 175, 165, 172]`.
2.  Hitung dan tampilkan nilai **median** (nilai tengah) dari `data_tinggi_badan_np_h5`. Simpan hasilnya dalam variabel **`median_tinggi_np_h5`**.
3.  Hitung dan tampilkan nilai **standar deviasi (standard deviation)** dari `data_tinggi_badan_np_h5` untuk melihat sebaran datanya. Simpan hasilnya dalam variabel **`std_dev_tinggi_np_h5`**.
4.  Tampilkan kedua variabel hasil tersebut dengan pesan yang jelas dan format nilai standar deviasi dengan **dua** angka di belakang koma.

In [18]:
data_tinggi_badan_np_h5 = np.array(
    [165, 170, 155, 180, 168, 175, 165, 172]
)

median_tinggi_np_h5 = np.median(data_tinggi_badan_np_h5)
std_dev_tinggi_np_h5 = np.std(data_tinggi_badan_np_h5)
print(
    f"Median tinggi badan: {median_tinggi_np_h5:.2f} cm\n"
    f"Standar deviasi tinggi badan: {std_dev_tinggi_np_h5:.2f} cm"
)

Median tinggi badan: 169.00 cm
Standar deviasi tinggi badan: 7.03 cm


### Soal 10: Rata-rata vs. Median dengan Data Pencilan

1.  Buatlah sebuah NumPy array bernama **`harga_properti_np_h5`** yang berisi data harga properti di suatu area (dalam Miliar Rupiah): `[1.2, 1.5, 1.1, 1.3, 1.6, 1.4, 15.0]`. Perhatikan ada satu nilai yang sangat tinggi (`15.0`) yang merupakan pencilan (outlier).
2.  Hitung nilai **rata-rata (mean)** dari `harga_properti_np_h5`. Simpan dalam variabel **`rata_rata_harga_np_h5`**.
3.  Hitung nilai **median** dari `harga_properti_np_h5`. Simpan dalam variabel **`median_harga_np_h5`**.
4.  Tampilkan `rata_rata_harga_np_h5` dan `median_harga_np_h5` dengan format dua angka desimal dan label yang jelas.
5.  Di bawah output angka, berikan komentar singkat (`#`) yang menjelaskan ukuran mana (rata-rata atau median) yang lebih baik dalam menggambarkan "harga properti yang tipikal" di area tersebut, dan jelaskan mengapa.

In [ ]:
harga_properti_np_h5 = np.array(
    [1.2, 1.5, 1.1, 1.3, 1.6, 1.4, 15.0]
)

rata_rata_harga_np_h5 = np.mean(harga_properti_np_h5)
median_harga_np_h5 = np.median(harga_properti_np_h5)
print(
    f"Rata-rata harga properti: {rata_rata_harga_np_h5:.2f} \n"
    f"Median harga properti: {median_harga_np_h5:.2f}"
)

# yang lebih baik dengan menggunakan median, karena median tidak terpengaruh oleh nilai ekstrem karna memang dalam prosesnya angka diurutkan berbeda dengan rata rata

Rata-rata harga properti: 3.30 
Median harga properti: 1.40


In [20]:
import math as m

import math

print(m.pi)

3.141592653589793
