### **Soal 1: Membuat dan Melakukan Operasi Aritmetika pada NumPy Array**

**Konteks:**
Anda adalah seorang ilmuwan data yang sedang menganalisis data konversi suhu. Anda memiliki daftar suhu dalam Celsius dan perlu mengubahnya menjadi Fahrenheit.

**Tugas:**

1.  Impor library NumPy dengan alias `np`.
2.  Buat sebuah list Python bernama `suhu_celsius_1` yang berisi data berikut: `[0, 15, 25, 30, 100]`.
3.  Konversikan list tersebut menjadi sebuah NumPy array bernama `np_suhu_celsius_1`.
4.  Buat array baru bernama `np_suhu_fahrenheit_1` dengan mengaplikasikan rumus konversi `(Celsius * 9/5) + 32` pada setiap elemen di `np_suhu_celsius_1`.
5.  Cetak `np_suhu_fahrenheit_1` untuk melihat hasilnya.

In [2]:
import numpy as np

suhu_celsius_1 = [
    0,
    15,
    25,
    30,
    100,
]

np_suhu_celsius_1 = np.array(suhu_celsius_1)
np_suhu_fahrenheit_1 = np.array(np_suhu_celsius_1 * 9/5) + 32
print(np_suhu_fahrenheit_1)

[ 32.  59.  77.  86. 212.]


### **Soal 2: Subsetting NumPy Array dengan Kondisi**

**Konteks:**
Dari data suhu Fahrenheit yang Anda miliki, Anda ingin menyaring dan menampilkan hanya suhu yang dianggap "panas" (di atas 80°F).

**Tugas:**

1.  Gunakan kembali NumPy array `np_suhu_fahrenheit_1` dari soal sebelumnya.
2.  Buat sebuah *boolean array* (sering disebut *mask*) yang akan bernilai `True` untuk setiap elemen di `np_suhu_fahrenheit_1` yang nilainya lebih besar dari `80`.
3.  Gunakan *mask* tersebut untuk memilih elemen-elemen dari `np_suhu_fahrenheit_1` yang memenuhi kondisi.
4.  Simpan hasilnya dalam array baru bernama `suhu_panas_2`.
5.  Cetak `suhu_panas_2`.

In [8]:
# numpy sudah diimport sebelumnya
mask = np_suhu_fahrenheit_1 > 80
suhu_panas_2 = np_suhu_fahrenheit_1[mask]

print(suhu_panas_2)

[ 86. 212.]


### **Soal 3: Membuat dan Mengakses Array 2D**

**Konteks:**
Anda sedang menganalisis data penjualan produk selama tiga hari. Data ini paling baik direpresentasikan dalam bentuk tabel atau array 2D, di mana baris mewakili hari dan kolom mewakili produk.

**Tugas:**

1.  Buat sebuah *list of lists* bernama `data_penjualan_3`:
    ```python
    data_penjualan_3 = [
        [10, 15, 12],  # Hari 1
        [11, 18, 14],  # Hari 2
        [14, 20, 17]   # Hari 3
    ]
    ```
2.  Konversikan `data_penjualan_3` menjadi sebuah NumPy array 2D bernama `np_penjualan_3`.
3.  Akses dan cetak data penjualan **produk ketiga** (indeks kolom 2) pada **hari kedua** (indeks baris 1).
4.  Akses dan cetak seluruh data penjualan untuk **hari ketiga** (seluruh baris di indeks 2).
5.  Akses dan cetak seluruh data penjualan untuk **produk pertama** (seluruh kolom di indeks 0).

In [14]:
# numpy sudah diimport sebelumnya

data_penjualan_3 = [
    [10, 15, 12],
    [11, 18, 14],
    [14, 20, 17],
]

np_penjualan_3 = np.array(data_penjualan_3)
print(np_penjualan_3[1, 2])
print(np_penjualan_3[2])
print(np_penjualan_3[:, 0])

14
[14 20 17]
[10 11 14]


### **Soal 4: Aritmetika pada Array 2D dan Statistik Dasar**

**Konteks:**
Anda memiliki data penjualan dari soal sebelumnya. Sekarang, Anda ingin menambahkan 5 unit ke setiap data penjualan sebagai bonus dan kemudian menghitung total penjualan per hari.

**Tugas:**

1.  Gunakan kembali array `np_penjualan_3`.
2.  Buat array baru bernama `np_penjualan_bonus_4` dengan menambahkan `5` ke setiap elemen di `np_penjualan_3`.
3.  Hitung **total penjualan** untuk **setiap hari** (setiap baris) dari array `np_penjualan_bonus_4`. Simpan hasilnya dalam variabel `total_harian_4`.
4.  Hitung **rata-rata penjualan** untuk **setiap produk** (setiap kolom) dari array `np_penjualan_bonus_4`. Simpan hasilnya dalam variabel `rata_rata_produk_4`.
5.  Cetak `np_penjualan_bonus_4`, `total_harian_4`, dan `rata_rata_produk_4`.

In [21]:
# numpy sudah diimport sebelumnya
np_penjualan_bonus_4 = np_penjualan_3 + 5
total_harian_4 = np.sum(np_penjualan_bonus_4, axis=1)
rata_rata_produk_4 = np.mean(np_penjualan_bonus_4, axis=0)

print(np_penjualan_bonus_4)
print(total_harian_4)
print(rata_rata_produk_4)

[[15 20 17]
 [16 23 19]
 [19 25 22]]
[52 58 66]
[16.66666667 22.66666667 19.33333333]


### **Soal 5: Statistik Lanjutan dan NumPy Side Effect**

**Konteks:**
Anda ingin membandingkan nilai penjualan rata-rata (*mean*) dengan nilai tengah (*median*) untuk setiap produk, karena median lebih tahan terhadap nilai pencilan (outlier). Anda juga akan menguji apa yang terjadi jika Anda mengubah sebagian data dari array asli.

**Tugas:**

1.  Gunakan kembali array `np_penjualan_3` yang asli.
2.  Buat sebuah *view* atau irisan dari `np_penjualan_3` yang hanya berisi data untuk **hari pertama** (baris 0). Simpan ini dalam variabel `penjualan_hari_pertama_5`.
3.  Ubah nilai **pertama** dalam `penjualan_hari_pertama_5` menjadi `100` untuk menyimulasikan outlier.
4.  Hitung **rata-rata** penjualan untuk setiap produk (per kolom) dari `np_penjualan_3` yang sudah termodifikasi. Simpan di `rata_rata_baru_5`.
5.  Hitung **median** penjualan untuk setiap produk (per kolom) dari `np_penjualan_3` yang sudah termodifikasi. Simpan di `median_baru_5`.
6.  Cetak `np_penjualan_3` yang baru, lalu cetak `rata_rata_baru_5` dan `median_baru_5`. Amati perbedaannya.

In [ ]:
# numpy sudah diimport sebelumnya

penjualan_hari_pertama_5 = np_penjualan_3[0]
penjualan_hari_pertama_5[0] = 100

rata_rata_baru_5 = np.mean(np_penjualan_3, axis=0)
median_baru_5 = np.median(np_penjualan_3, axis=0)

print(np_penjualan_3)
print(rata_rata_baru_5)
print(median_baru_5)


[[100  15  12]
 [ 11  18  14]
 [ 14  20  17]]
[41.66666667 17.66666667 14.33333333]
[14. 18. 14.]


### **Soal 6: Mengubah Bentuk Array (`.reshape()`)**

**Konteks:**
Anda menerima data sensor sebagai satu baris panjang (array 1D), tetapi Anda tahu bahwa data tersebut sebenarnya mewakili pengukuran dari 3 sensor yang berbeda selama 4 hari. Anda perlu mengubah bentuk array tersebut menjadi 2D (4 baris, 3 kolom) untuk analisis lebih lanjut.

**Tugas:**

1.  Buat sebuah NumPy array 1D bernama `data_sensor_flat_6` yang berisi 12 elemen:
    ```python
    data_sensor_flat_6 = np.array([10, 12, 11, 20, 22, 21, 30, 29, 31, 41, 40, 42])
    ```
2.  Gunakan method `.reshape()` pada array tersebut untuk mengubah bentuknya menjadi 4 baris dan 3 kolom.
3.  Simpan array 2D yang baru ke dalam variabel `data_sensor_reshaped_6`.
4.  Cetak `data_sensor_reshaped_6` dan `data_sensor_reshaped_6.shape` untuk memverifikasi hasilnya.

In [ ]:
# numpy sudah diimport sebelumnya
data_sensor_flat_6 = np.array([
    10, 12, 11, 20, 22, 21,
    30, 29, 31, 41, 40, 42,
])

data_sensor_reshaped_6 = data_sensor_flat_6.reshape(4, 3)
print(data_sensor_reshaped_6)
print(data_sensor_reshaped_6.shape)

[[10 12 11]
 [20 22 21]
 [30 29 31]
 [41 40 42]]
(4, 3)


### **Soal 7: Menggabungkan Array (`np.vstack` dan `np.hstack`)**

**Konteks:**
Anda memiliki data penjualan dari dua minggu yang berbeda, masing-masing disimpan dalam array terpisah. Anda perlu menggabungkannya menjadi satu dataset yang utuh. Anda akan mencoba dua cara: menggabungkan secara vertikal (menumpuk baris) dan secara horizontal (menjajarkan kolom).

**Tugas:**

1.  Buat dua NumPy array 2D:
    ```python
    minggu1_7 = np.array([[10, 12], [15, 18]]) # Penjualan 2 produk selama 2 hari
    minggu2_7 = np.array([[11, 14], [16, 17]]) # Penjualan 2 produk selama 2 hari berikutnya
    ```
2.  Gunakan `np.vstack()` (vertical stack) untuk menumpuk `minggu2_7` di bawah `minggu1_7`. Simpan hasilnya di `penjualan_vertikal_7`. Hasilnya akan menjadi array 4x2.
3.  Gunakan `np.hstack()` (horizontal stack) untuk menjajarkan `minggu2_7` di samping `minggu1_7`. Simpan hasilnya di `penjualan_horizontal_7`. Hasilnya akan menjadi array 2x4.
4.  Cetak kedua hasil penggabungan tersebut.

In [ ]:
# numpy sudah diimport sebelumnya
minggu1_7 = np.array([
    [10, 12],
    [15, 18],
])
minggu2_7 = np.array([
    [11, 14],
    [16, 17],
])

penjualan_vertikal_7 = np.vstack((minggu1_7, minggu2_7))
penjualan_horizontal_7 = np.hstack((minggu1_7, minggu2_7))

print(penjualan_vertikal_7)
print(penjualan_horizontal_7)

[[10 12]
 [15 18]
 [11 14]
 [16 17]]
[[10 12 11 14]
 [15 18 16 17]]


### **Soal 8: Mengurutkan NumPy Array**

**Konteks:**
Anda memiliki data skor acak dari beberapa pemain. Anda perlu mengurutkannya dari yang terendah ke tertinggi. Selain itu, Anda memiliki data skor 2D (beberapa game) dan ingin mengurutkan skor di setiap game secara independen.

**Tugas:**

1.  Buat sebuah array 1D berisi skor acak:
    ```python
    skor_acak_8 = np.array([150, 125, 180, 140, 165])
    ```
2.  Gunakan fungsi `np.sort()` untuk mengurutkan `skor_acak_8`. Simpan hasilnya di `skor_terurut_8` dan cetak.
3.  Sekarang, buat array 2D:
    ```python
    skor_game_8 = np.array([
        [150, 130, 180], # Game 1
        [145, 190, 160]  # Game 2
    ])
    ```
4.  Urutkan data **di dalam setiap baris** (urutkan skor per game). Simpan hasilnya di `skor_terurut_per_game_8` dan cetak.

In [30]:
# numpy sudah diimport sebelumnya
skor_acak_8 = np.array([
    150,
    125,
    180,
    140,
    165,
])

skor_terurut_8 = np.sort(skor_acak_8)
print(skor_terurut_8)
skor_game_8 = np.array([
    [150, 130, 180],
    [145, 190, 160],
])

skor_terurut_per_game_8 = np.sort(skor_game_8, axis=1)
print(skor_terurut_per_game_8)



[125 140 150 165 180]
[[130 150 180]
 [145 160 190]]


### **Soal 9: Pemilihan Kondisional dengan `np.where()`**

**Konteks:**
Anda memiliki data skor ujian siswa. Anda ingin mengganti semua skor di bawah 70 dengan nilai 0 (gagal), dan membiarkan sisanya tetap utuh. Fungsi `np.where()` sangat ideal untuk tugas "jika-maka-lain" seperti ini.

**Tugas:**

1.  Buat sebuah NumPy array bernama `skor_ujian_9`:
    ```python
    skor_ujian_9 = np.array([88, 65, 92, 71, 59, 81, 75, 68])
    ```
2.  Gunakan `np.where()` untuk membuat array baru bernama `skor_final_9`.
3.  Logikanya adalah: **jika** nilai dalam `skor_ujian_9` kurang dari 70, **maka** gunakan nilai `0`, **jika tidak** gunakan nilai asli dari `skor_ujian_9`.
4.  Cetak `skor_final_9` untuk melihat hasilnya.

In [31]:
# numpy sudah diimport sebelumnya
skor_ujian_9 = np.array([
    88, 65, 92, 71,
    59, 91, 75, 68,
])

skor_final_9 = np.where(skor_ujian_9 < 70, 0, skor_ujian_9)
print(skor_final_9)

[88  0 92 71  0 91 75  0]


### **Soal 10: Analisis Data Gabungan**

**Konteks:**
Anda menerima data penjualan mingguan untuk 2 produk selama 3 minggu sebagai satu array 1D. Anda perlu mengubahnya menjadi array 2D, menghitung penjualan rata-rata per minggu, dan kemudian menghitung selisih penjualan setiap hari terhadap rata-rata mingguannya.

**Tugas:**

1.  Buat sebuah NumPy array 1D bernama `penjualan_flat_10` yang berisi data penjualan:
    ```python
    # Minggu 1 (Produk A, B), Minggu 2 (A, B), Minggu 3 (A, B)
    np.array([100, 110, 120, 130, 105, 115])
    ```
2.  Ubah bentuk `penjualan_flat_10` menjadi array 2D dengan 3 baris (minggu) dan 2 kolom (produk). Simpan di `penjualan_mingguan_10`.
3.  Hitung **penjualan rata-rata** untuk **setiap minggu** (per baris). Hasilnya akan menjadi array 1D dengan 3 elemen.
4.  Ubah bentuk array rata-rata tersebut agar menjadi array 2D berukuran 3x1 agar bisa dilakukan *broadcasting*.
5.  Hitung `selisih_dari_rata_rata_10` dengan mengurangkan `penjualan_mingguan_10` dengan array rata-rata yang sudah diubah bentuknya.
6.  Cetak `penjualan_mingguan_10`, rata-rata penjualan per minggu, dan `selisih_dari_rata_rata_10`.

In [38]:
penjualan_flat_10 = np.array([
    100, 110, 120,
    130, 105, 115,
])

penjualan_mingguan_10 = penjualan_flat_10.reshape(3, 2)
rata_rata = np.mean(penjualan_mingguan_10, axis=1)
ubah_bentuk = rata_rata.reshape(3, 1)

selisih_dari_rata_rata_10 = penjualan_mingguan_10 - ubah_bentuk
print(penjualan_mingguan_10)
print(ubah_bentuk)
print(selisih_dari_rata_rata_10)

[[100 110]
 [120 130]
 [105 115]]
[[105.]
 [125.]
 [110.]]
[[-5.  5.]
 [-5.  5.]
 [-5.  5.]]
