## Type of NumPy Arrays

In [1]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

In [2]:
print(type(np_height))

<class 'numpy.ndarray'>


In [3]:
print(type(np_weight))

<class 'numpy.ndarray'>


# 2D NumPy Arrays

In [9]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]


In [ ]:
print(np_2d.shape) # 2 rows 5 columns

(2, 5)


In [ ]:
# np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  #[65.4, 59.2, 63.6, 88.4, "68.7"]])
# What if we change last element with str
# print(np_2d)

[['1.73' '1.68' '1.71' '1.89' '1.79']
 ['65.4' '59.2' '63.6' '88.4' '68.7']]


In [10]:
print(np_2d)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]


## Subsetting

In [11]:
print(np_2d[0][2])

1.71


In [12]:
# alternatif way using comma
print(np_2d[0, 2])

1.71


In [13]:
print(np_2d[:, 1:3])

[[ 1.68  1.71]
 [59.2  63.6 ]]


In [14]:
print(np_2d[1, :])

[65.4 59.2 63.6 88.4 68.7]
